# Generated by Django 3.2.9 on 2021-11-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachtment',
            field=models.ImageField(null=True, upload_to='attachments'),
        ),
    ]
