# Generated by Django 3.2.9 on 2021-11-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_mesa', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
