# Generated by Django 3.2.9 on 2021-11-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211106_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_info',
            field=models.TextField(null=True),
        ),
    ]
